### ISSUE TITLE
make move sensitive

### ISSUE THREAD

**Issue by hackwin** [sparkfun/Blackberry_Trackballer_Breakout#4]
is there a way to increase the sensitivity so a small movement on the trackball triggers a large change in up/down left/right?

**Comment by ToniCorinne** [comment]
If you simply want a larger change in up/down/left/right, you can update the position variables to scale by more than 1 unit with each register of a change in the code.

For example:
     ` if (mouse_Lft > 0)
  {
    x_position= --x_position;
}`

could be changed to
` if (mouse_Lft > 0)
  {
    x_position= x_position-8;
}`
if you wanted to scale the positioning to change 8x more quickly. Otherwise, you'd need to be working on a microcontroller that you could map up/down/left/right to interrupt pins and play with the sensitivity and scaling from there.

**Comment by hackwin** [comment]
thanks, i did using an arduino mega: https://codebender.cc/sketch:348904

the module worked as a computer mouse by using Processing/Java to mouse the mouse.

http://pastebin.com/6W6m0gQG

**Comment by bboyho** [comment]
It looks like this issue was addressed. I am closing it outl. =)
